SIO/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'app.views.home', name='home'),
    url(r'^empresas/(?P<page>\d+)', 'clientes.views.index', name='empresas'),
    url(r'^criar-empresa/', 'clientes.views.create', name='criar-empresa'),
    url(r'^detalhes-empresa/(?P<empresa_id>\d+)', 'clientes.views.details', name='detalhes-empresa'),
    url(r'^apagar-empresa/(?P<empresa_id>\d+)', 'clientes.views.delete', name='apagar-empresa'),
    url(r'^produtos/(?P<page>\d+)', 'produtos.views.index', name='produtos'),
    url(r'^criar-produto/', 'produtos.views.create', name='criar-produto'),
    url(r'^detalhes-produto/(?P<produto_id>\d+)', 'produtos.views.details', name='detalhes-produto'),
    url(r'^editar-produto/(?P<produto_id>\d+)', 'produtos.views.edit', name='editar-produto'),
    url(r'^apagar-produto/(?P<produto_id>\d+)', 'produtos.views.delete', name='apagar-produto'),
    url(r'^servicos/(?P<page>\d+)', 'servicos.views.index', name='servicos'),
    url(r'criar-servico/', 'servicos.views.create', name='criar-servico'),
    url(r'detalhes-servico/(?P<servico_id>\d+)', 'servicos.views.details', name='detalhes-servico'),
    url(r'editar-servico/(?P<servico_id>\d+)', 'servicos.views.edit', name='editar-servico'),
    url(r'apagar-servico/(?P<servico_id>\d+)', 'servicos.views.delete', name='apagar-servico'),
    url(r'orcamentos/(?P<page>\d+)', 'orcamentos.views.index', name='orcamentos'),
    url(r'orcamentos/(?P<page>\d+)/(?P<Search>\w+)', 'orcamentos.views.index', name='orcamentos-busca'),
    url(r'criar-orcamento/', 'orcamentos.views.create', name='criar-orcamento'),
    url(r'detalhes-orcamento/(?P<orcamento_id>\d+)', 'orcamentos.views.details', name='detalhes-orcamento'),
    url(r'exportar/(?P<orcamento_id>\d+)','orcamentos.views.export', name='exportar'),
    url(r'propostas/(?P<page>\d+)', 'propostas.views.index', name='propostas'),
    url(r'criar-proposta/', 'propostas.views.create', name='criar-proposta'),
    url(r'editar-proposta/(?P<proposta_id>\d+)', 'propostas.views.edit', name='editar-proposta'),
    url(r'apagar-orcamento/(?P<orcamento_id>\d+)', 'orcamentos.views.delete', name='apagar-orcamento'),
    url(r'editar-orcamento/(?P<orcamento_id>\d+)', 'orcamentos.views.edit', name='editar-orcamento')
)

clientes/models.py
from __future__ import unicode_literals

from django.db import models


class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=150)
    cep = models.CharField(max_length=20)
    municipio = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    CNPJ = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100)
    datacadastro = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return str(self.nome)


class Telefone(models.Model):
    numero = models.CharField(max_length=20)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    datacadastro = models.DateField(auto_now=True, null=True)

clientes/forms.py
# coding=utf-8
from django import forms

from .models import Empresa, Telefone


class TelefoneForm(forms.Form):
    numero = forms.CharField(max_length=100, widget=forms.TextInput({'placeholder': 'Número', 'class': 'form-control'}))


class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = "__all__"
        widgets = {
            'nome': forms.TextInput({'placeholder': 'Nome', 'class': 'form-control'}),
            'endereco': forms.TextInput({'placeholder': 'Endereço', 'class': 'form-control'}),
            'cep': forms.TextInput({'placeholder': 'CEP', 'class': 'form-control'}),
            'municipio': forms.TextInput({'placeholder': 'Munícipio', 'class': 'form-control'}),
            'estado': forms.TextInput({'placeholder': 'UF', 'class': 'form-control'}),
            'email': forms.EmailInput({'placeholder': 'Email', 'class': 'form-control'}),
            'CNPJ': forms.TextInput({'placeholder': 'CNPJ', 'class': 'form-control'})

        }

clientes/views.py
from django.shortcuts import render
from .models import Empresa, Telefone
from django.core.paginator import Paginator
from .forms import TelefoneForm, EmpresaForm
from django.shortcuts import get_object_or_404


# Create your views here.

def index(request, page=None):
    page = page or 1
    lista = Empresa.objects.all()
    paginator = Paginator(lista, 10)
    pagedList = paginator.page(page)
    return render(request, 'clientes/index.html', {'empresas': pagedList, 'title': 'Lista de Empresas'})


def create(request):
    form = EmpresaForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            empresa = form.save()
            telefones = request.POST.getlist('telefone')
            for telefone in telefones:
                tel = Telefone(numero=telefone, empresa=empresa)
                tel.save()
            return index(request)
    return render(request, 'clientes/create.html', {'form': form, 'title': 'criar empresa'})


def details(request, empresa_id):
    empresa = get_object_or_404(Empresa, pk=empresa_id)
    telefones = Telefone.objects.filter(empresa=empresa)
    return render(request, 'clientes/details.html', {'empresa': empresa, 'telefones': telefones, 'title' : 'Detalhes de empresa'})


def delete(request, empresa_id):
    empresa = get_object_or_404(Empresa, pk=empresa_id)
    empresa.delete()
    return index(request)

app/templates/clientes/create.html
{% extends 'layout.html' %}

{% block content %}
<div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">
            Nova empresa

            </h3>

        </div>
        <div class="box-body">
            {% if form.errors %}
                {% for erro in form.errors %}
                    <p>{{ erro }}</p>
                {% endfor %}
            {% endif %}

             <form action="" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                <div class="box-body">
                    <div class="form-group">
                        {{ form.nome.label_tag }}
                        {{ form.nome }}
                    </div>
                     <div class="form-group">
                        {{ form.CNPJ.label_tag }}
                        {{ form.CNPJ }}
                    </div>
                    <div class="form-group">
                        {{ form.endereco.label_tag }}
                        {{ form.endereco }}
                    </div>
                    <div class="form-group">
                        {{ form.cep.label_tag }}
                        {{ form.cep }}
                    </div>
                     <div class="form-group">
                        {{ form.municipio.label_tag }}
                         {{ form.municipio }}
                    </div>
                     <div class="form-group">
                        {{ form.estado.label_tag }}
                         {{ form.estado }}
                    </div>
                     <div class="form-group">
                        {{ form.email.label_tag }}
                         {{ form.email }}
                    </div>
                    <div class="form-group">
                        <div id="telefones" class="input-group">
                            <label>Telefones:</label>
                            <input type="text" name="telefone" class="form-control" placeholder="Telefone" \>

                        </div>
                        <div class="pull-right">
                            <a class="btn btn-success pull-right" id="add-telefone" href="#"><i class="fa fa-plus"></i></a>
                        </div>

                    </div>

                </div>

                 <div class="box box-footer">
                    <input type="submit" class="btn btn-success" value="Enviar"/>
                    <a href="{% url 'empresas' page=1 %}" class="btn btn-info">Voltar</a>
                </div>
            </form>


        </div>


    </div>

    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
           new dgCidadesEstados({
               cidade: document.getElementById("id_municipio"),
               estado: document.getElementById("id_estado")
           })
        });
        $('#id_cep').mask('00000-000');
        $('input[name="telefone"]').mask('(00)00000-0000');
        $('#id_CNPJ').mask('00.000.000/0000-00')
        $('#add-telefone').click(function(e){
            e.preventDefault();

            $('#telefones').append('<input type="text" style="margin-top:10px" name="telefone" class="form-control" placeholder="Telefone" \>')
            $('input[name="telefone"]').mask('(00)00000-0000');
        });
    </script>

{% endblock %}

app/templates/clientes/details.html
{% extends 'layout.html' %}

{% block content %}
    <section class="content-header">
        <h1>Detalhes de Empresa</h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        <h3>Detalhes</h3>
                    </div>
                    <div class="box-content padded">
                        <table class="table table-bordered table-striped responsive">
                            <tbody>
                            <tr>
                                <td>Nome</td>
                                <td>{{ empresa.nome }}</td>
                            </tr>
                            <tr>
                                <td>Endereco</td>
                                <td>{{ empresa.endereco }}</td>
                            </tr>
                            <tr>
                                <td>CEP</td>
                                <td>{{ empresa.cep }}</td>
                            </tr>
                            <tr>
                                <td>Município</td>
                                <td>{{ empresa.municipio }}</td>
                            </tr>
                            <tr>
                                <td>Estado</td>
                                <td>{{ empresa.estado }}</td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>{{ empresa.email }}</td>
                            </tr>
                            {% if telefones %}
                            <tr>
                            <td>Telefones</td>
                            <td>
                                {% for telefone in telefones %}
                                    <p>
                                {{ telefone.numero }}
                                    </p>
                                {% endfor %}
                            </td>
                            </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer">
                        <a href="{% url 'empresas' page=1 %}" class="btn btn-info">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </section>



{% endblock %}

app/templates/clientes/index.html
{% extends 'layout.html' %}

{% block content %}
<section class="content">

<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Clientes</h3>
                <div class="pull-right">
                    <a href="{% url 'criar-empresa' %}" class="btn btn-success pull-right">
                        <i class="fa fa-plus-circle white"></i>
                        Nova empresa</a>
                </div>
            </div>

            <!-- /.box-header -->
            <div class="box-body">
              <div class="dataTables_wrapper form-inline dt-bootstrap" id="example2_wrapper"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table aria-describedby="example2_info" role="grid" id="example2" class="table table-bordered table-hover dataTable">
                <thead>
                <tr role="row">
                    <th aria-label="Rendering engine: activate to sort column descending" aria-sort="ascending" colspan="1" rowspan="1" aria-controls="example2" tabindex="0" class="sorting_asc">Nome</th>
                    <th aria-label="Browser: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="example2" tabindex="0" class="sorting">Email</th>
                    <th aria-label="Browser: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="example2" tabindex="0" class="sorting">Muncípio</th>
                    <th aria-label="Browser: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="example2" tabindex="0" class="sorting">Estado</th>
                    <th style="text-align: right;" aria-label="Engine version: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="example2" tabindex="0" class="sorting">Ações</th>
                </thead>
                <tbody>
                    {% if empresas %}
                        {% for empresa in empresas %}
                        <tr>
                            <td>{{ empresa.nome }}</td>
                            <td>{{ empresa.email }}</td>
                            <td>{{ empresa.municipio }}</td>
                            <td>{{ empresa.estado }}</td>
                           
                            <td>
                            <div class="pull-right">
                                <a href="{% url 'detalhes-empresa' empresa_id=empresa.id %}" class="btn bg-olive btn-small">
                                    <i class="fa fa-search-plus"></i>
                                </a>
                                <a href="" class="btn btn-warning btn-small">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="{% url 'apagar-empresa' empresa_id=empresa.id %}" class="btn btn-danger btn-small">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </div>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td style="text-align:center;" colspan="5">Nenhum item encontrado.</td>
                        </tr>
                    {% endif %}
                </tbody>

              </table>
               <div class="box-footer clearfix no-border">
                  <div style="text-align:center;" class="pagination-container">
                  <ul class="pagination">
                      {% for page in empresas.paginator.page_range %}
                      <li class="{% if page == empresas.number%}active{% endif %}">

                            <a href="{% url 'empresas' page=page %}">{{ page }}</a>

                        </li>
                        {% endfor %}

                    </ul>
                  </div>
              </div>

              </div></div>

            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
</section>
{% endblock %}